### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by roblane-msft** [okieselbach/SyncMLViewer#3]
Hi Oliver - with the additional of background tracing being very useful would it be possible to have SyncMLviewer command line args to 
1) start a tracing session
2) enable background tracing
3) trigger a sync?

I've been looking at VPN mdm policy related issue during the user portion of ESP and it's been a total pain trying to capture what the device is getting from / sending back to Intune.

Cheers
Rob

**Comment by okieselbach** [comment]
Sorry for my delay, I missed the issue 🙈. That's a good point, I will have a look into this how I can provide this.

**Comment by roblane-msft** [comment]
No worries Oliver, completely understand - there's a day job to do!!! 🙂
________________________________

**Comment by okieselbach** [comment]
Hi,

I added command line arguments support in the release v1.1.1
https://github.com/okieselbach/SyncMLViewer/releases/tag/v1.1.1

You can use command line switches to trigger action right from the start:

/s   ...start MDM sync
/m   ...start MMP-C sync
/b   ...start in background logging mode
/h   ...hide window immediately

best,
Oliver

**Comment by roblane-msft** [comment]
Fabulous! Thanks Oliver – will test it out immediately 😊

**Comment by okieselbach** [comment]
I think it is fine at the moment with the current implementation. I'm going to close it for now. If there is something, the issue can be reopened easily.
